# Site settings
name: Home
email: jackson0530@yonsei.ac.kr
url: url
description: "Blog and projects and studies"
author: "Sangwoo Park"
title: "BlogFolio"
permalink: pretty
baseurl: ""

# social
github:
  username: psw0021

twitter:
  username: SangwooSC30