# Site settings
name: Home
email: jackson0530@yonsei.ac.kr
url: url
description: "Sangwoo's Blog and studies"
author: "Sangwoo Park"
title: "Sangwoo's Blog"
permalink: pretty
baseurl: ""

# social
github:
  username: psw0021

twitter:
  username: SangwooSC30