# Site settings
name: name
email: email
url: url
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: ""

# social
github:
  username: psw0021

twitter:
  username: username